# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'PO Box 34'
description:      'Connecting voices inside with voices outside'
url:              'https://pobox34.github.io'
baseurl:          '/pobox-34'
copyright:        'All rights reserved, 2021'
logo:             'logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  posts:
    output: true
    layout: 'post'
  writers:
    output: true
    layout: 'writer'
  works: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'work' # the layout for the pages to use
    metadata:
      source: 'works.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/works' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      works:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - writer
          - label
          - _date

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'About the Project'
        link: '/about'
      - label: 'Hidden Lives Illuminated'
        link: '/hidden-lives-illuminated'
      - label: 'Team'
        link: '/team'
  - label: 'Writers'
    sub:
      - label: 'Aaron W'
        link: '/writers/aaron-w/'
      - label: 'Alexander S'
        link: '/writers/alexander-s/'
      - label: 'Clarence S'
        link: 'writers/clarence-s/'
      - label: 'David G'
        link: '/writers/david-g/'
      - label: 'Donyea P'
        link: 'writers/donyea-p/'
      - label: 'Ezra B'
        link: '/writers/ezra-b/'
      - label: 'Joseph K'
        link: '/writers/joseph-k/'
      - label: 'Joseph S'
        link: '/writers/joseph-s/'
      - label: 'Justino G'
        link: '/writers/justino-g/'
      - label: 'Marvin S'
        link: '/writers/marvin-s/'
      - label: 'Myke L'
        link: '/writers/myke-l/'
      - label: 'Paul M'
        link: '/writers/paul-m/'
      - label: 'Quasheam R'
        link: '/writers/quasheam-r/'
  - label: 'Browse'
    sub:
      - label: 'Browse the Collection'
        link: '/collection/'
      - label: 'Covid Responses'
        link: '/covid-responses/'
  - label: 'Blog'
    link: '/blog/'
  - label: 'Search'
    link: '/search/'
  - label: 'Support'
    sub:
      - label: 'Write to the Writers'
        link: '/mailing-addresses/'
      - label: 'Support the Project'
        link: '/support/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/pobox34/pobox-34'
    - label: 'Team'
      link: '/team'
  logos:
    - img: 'logo.png'

# --------------------------------------------------------------
# SITE ABOUT SETTINGS
# --------------------------------------------------------------
#

about:
  logos:
    - label: 'Annenberg School for Communication'
      img: 'img/logos/annenberg_logo.jpg'
      link: 'https://www.asc.upenn.edu/'
    - label: 'University of Pennsylvania'
      img: 'img/logos/UniversityofPennsylvania_FullLogo_RGB.jpg'
      link: 'https://www.upenn.edu/'
    - label: 'Campaign for Community'
      img: 'img/logos/campaign_for_community_logo.jpg'
      link: 'https://provost.upenn.edu/campaign-community'
    - label: 'Wolf Center for Humanities'
      img: 'img/logos/wolf_logo.png'
      link: 'https://wolfhumanities.upenn.edu/'
    - label: 'Price Lab for Digital Humanities'
      img: 'img/logos/price_lab_logo.png'
      link: 'https://pricelab.sas.upenn.edu/'


# FIN
